"""
Bulk real-life situations PART 3: ~29 archetypes x 30 variants ≈ 870.
Includes NEW tags for the new sync branches: money, smartass, defiant,
her-day (he asks about HER day), breakup.
Mostly English, minimal Hinglish. Real-chat style.
"""
BULK3 = [
("miss-you", [
 "miss your cuddles", "when are we meeting next", "plan something soon na",
 "miss our video calls", "need you beside me", "miss your teasing",
 "alone + bored = missing you", "miss your morning voice",
 "wish weekends were longer with you", "miss your hand in mine",
 "your laugh is my fav sound, miss it", "miss fighting then patching up",
 "distance makes my heart ache", "miss your surprise texts",
 "remember our first rain walk? miss that", "miss your sleepy voice",
 "phone gallery = you. miss you more", "miss your cooking (and you)",
 "weekdays drag without you", "miss your long hugs",
 "if missing you was a job, I'm CEO", "miss your random calls",
 "your spot beside me is empty", "miss your goodnight voice",
 "wish I could pause time with you", "miss your silly faces",
 "every love song = you. missing hard", "miss your care packages",
 "come over? please? 🥺", "miss my crime partner",
]),
("compliment", [
 "you're my peace", "that kurti pic = wow", "your smile heals me",
 "so proud of my girl", "you're effortlessly pretty", "brains + beauty = you",
 "that haircut suits you!", "you look happy, love that", "your vibe attracts",
 "cutest angry face btw 😌", "you're my favorite view", "that laugh, again please",
 "you make simple look stunning", "your confidence = attractive",
 "best smile award: you", "you're glowing these days", "that voice note replayed 5x",
 "you're my muse", "pretty + kind = rare", "that ethnic look killed me",
 "you're the moment 😌", "flawless, as usual", "your eyes tell stories",
 "that candid pic = perfect", "you're my favorite person, obviously",
 "charm overload", "you're beautiful inside out", "that giggle = music",
 "you're a masterpiece", "my eyes search only you",
]),
("thinking-of-you", [
 "that joke you cracked, still laughing", "your fav ice cream flavor launched new pack",
 "saw your doppelganger, double-take 😭", "that place we said we'd visit = open now",
 "heard your name in a song lyric", "that filter you love = trending again",
 "saw a kid with your exact pout", "your comfort movie is on TV",
 "that street dog we fed, saw again", "bought the chips you like",
 "that ramp walk video = you energy", "saw a proposal, thought of ours someday",
 "your hometown food festival is on", "that old song = our car rides",
 "saw lightning, wished you near", "that bookstore we planned, walked past",
 "your fav season started 🌧️", "saw twins fighting like us 😭",
 "that dialogue = your life motto", "moon tonight, classic us moment",
 "saw a hoodie your size, almost bought", "that game you rage at = update out",
 "old chat screenshots, smiling now", "that tree we carved initials? visited",
 "saw your school, thought of stories", "that dish you cook = ordered it",
 "traffic + your playlist = bearable", "that meme page posted your vibe",
 "saw fireworks, wished your hand in mine", "everything loops back to you",
]),
("proud-thanks", [
 "you're my strength", "thanks for the pep talk", "nailed that advice, thanks",
 "proud of your patience with me", "thanks for the midnight maggie run",
 "you're my safe space", "thanks for handling my mood swings",
 "proud of your new habit", "thanks for the honest mirror",
 "you push me to grow", "thanks for the surprise visit",
 "proud of your cooking glow-up", "thanks for defending me",
 "you're my biggest supporter", "thanks for the rainy-day rescue",
 "proud of your work ethic", "thanks for the calm in my chaos",
 "you're my clarity", "thanks for the 2am talk",
 "proud of your kindness to strangers", "thanks for the playlist on loop",
 "you're my home base", "thanks for the festival planning",
 "proud of your exam prep", "thanks for the gym motivation",
 "you're my light", "thanks for the family handling",
 "proud of your art", "thanks for existing, really",
]),
("future-talk", [
 "imagine our Goa trip? someday", "imagine our Diwali together 🪔",
 "our kids will have your smile", "retire early, travel with you?",
 "our balcony garden plan 🌱", "imagine slow mornings, our home",
 "we'll adopt a dog, name him... you pick", "our anniversary in Paris? manifesting",
 "imagine cooking together daily", "our road trip playlist is ready",
 "growing old, still teasing you 😌", "our home will smell like rain + chai",
 "imagine festivals at our place", "we'll have a movie room, promise",
 "our mornings: chai + newspaper + you", "imagine meeting as grandparents' story",
 "we'll travel every anniversary", "our kid's first word: mumma? 😌",
 "imagine us debt-free + beachside", "our love story = novel material",
 "we'll open a cafe? daydreaming", "imagine slow dancing at 60 🥺",
 "our terrace movie nights, forever", "we'll laugh at today's fights later",
 "imagine matching hoodies at 50 😌", "our holiday traditions loading...",
 "we'll tell our story proudly", "imagine peace. that's us.",
 "our forever starts daily", "we'll make it, I feel it ❤️",
]),
("surprise-plan", [
 "check your doorstep in 10 👀", "dinner reservation done. dress up 😌",
 "weekend getaway booked!! guess where", "gift arriving friday 🎁",
 "your fav dessert is on its way 🧁", "tickets to that show you wanted!!",
 "look outside your window 👀", "surprise video call party? almost",
 "booked that restaurant finally!", "flowers every friday from now 🌹",
 "planned a picnic, just say yes", "your wishlist item: ordered ✅",
 "spa voucher in your mail 💌", "concert + front row. you're welcome 😌",
 "breakfast surprise tomorrow 8am?", "letter coming by post, old school 💌",
 "midnight surprise call tonight?", "your mom's in on the surprise too 😌",
 "anniversary plan loading... shhh", "ice cream truck bribed for you 🍦",
 "that bag you eyed? surprise 🎒", "weekend = no plans but mine for you",
 "candlelight dinner at home? I cook 😌", "your fav movie + projector night?",
 "surprise guest: me, at 7 😌", "gift wrapped in 3 layers, good luck",
 "planned nothing. that's the surprise 😌", "check your playlist, added our song",
 "surprise hug attack incoming", "your day = about to get better",
]),
("small-talk", [
 "office gossip: boss danced at party 😭", "auto driver gave life advice today",
 "tried new ramen place, mid", "pigeons fought on my balcony, cinema 🐦",
 "my plant grew a new leaf!! 🌱", "rickshaw ran out of CNG, walked 2km",
 "saw an uncle feeding 20 dogs ❤️", "metro was empty today, eerie",
 "burnt toast again. talent?", "neighbor's cat adopted me officially",
 "power cut + candles = vibe 🕯️", "found 100 bucks in old jeans!!",
 "colleague microwaved fish. war.", "saw a rainbow on commute 🌈",
 "my code finally worked!! 🎉", "slept through 3 alarms, oops",
 "street vendor gave extra free 😌", "saw a wedding baraat, danced a little",
 "lost my pen, found it in hair (not mine)", "wifi died mid-meeting, freedom",
 "tasted weird combo: maggie + chocolate", "saw shooting star, wished you",
 "my team won!! screaming 🎉", "got caught singing in traffic 😭",
 "new neighbor bakes, smell = heaven", "found our old movie stub 🎬",
 "elevator stuck 10 mins, survived", "saw a cute baby, baby fever? 😌",
 "clouds look like cotton candy today", "day was chaos, telling you everything",
]),
("exam-fear", [
 "maths exam tomorrow, pray for me", "viva voce, professors scary 😭",
 "group project, I'm doing everything", "backlog fear is real",
 "placement test sunday, nervous", "coding round tonight, wish luck",
 "semester fees stress", "attendance short, tension",
 "thesis deadline extended? please?", "lab exam, break everything (not)",
 "CAT prep killing me", "UPSC dream vs sleep schedule",
 "board exam flashbacks", "practical files pending 😭",
 "scholarship interview friday", "rank anxiety max", "peer pressure real",
 "study group ditched me", "library seat wars daily", "notes incomplete, panic",
 "professor hates me, I feel it", "online exam, tech fear", "cheat sheet dreams (kidding)",
 "all-nighter #3 this week", "coffee IV drip needed ☕", "exam hall nightmares",
 "revision zero, confidence zero", "parents asking marks daily 🙄",
 "topper friend flexing again", "exam + love life balance? how",
]),
("kiss-hug", [
 "kiss quota pending 😘", "hug attack in 3...2...1", "steal a kiss? okay taking 😘",
 "one hug = full day energy", "kiss me quick before I leave", "group hug? just us two 😌",
 "hug me like the movies", "forehead kiss tax: paid 😘", "cheek kiss checkpoint ✅",
 "bear hug needed urgently 🐻", "kiss + forehead combo meal 😌",
 "hug me through the phone (try)", "sneak a kiss at the signal? 😘",
 "hug longer today please", "kiss on the nose? boop 😘",
 "farewell hug, extra tight", "reunion hug loading...", "hug me, bad day shield",
 "kiss me, good luck charm 😘", "pocket-size hugs daily", "hug first, world later",
 "kiss cam moment, it's us 😘", "squeeze the stress out, hug me",
 "hug + twirl like films? 😌", "morning hug ritual when together",
 "kiss goodnight over call? 😘", "hug pending since monday", "virtual hug delivered 📦❤️",
 "kiss me, I'm yours anyway", "hug = home",
]),
("hold-hands", [
 "fingers interlocked? yes please", "hold hands in the rain 🌧️",
 "your palm + my palm = perfect", "swing our hands while walking? 😌",
 "hold hands during the scary scene", "hand-hold tax at every signal 🚦",
 "your hand is my favorite hold", "don't let go, ever", "hand in pocket together?",
 "hold hands + silent walk = best", "your thumb drawing circles >>>",
 "hold my hand, I'm nervous", "crowd = hand-hold mode on", "sweaty palms, still holding 😌",
 "hold hands like day one", "your hand fits like home", "hand squeeze = I love you code",
 "hold hands across the table? 😌", "walking + holding = therapy",
 "your hand, my jacket pocket, winter ❄️", "hold hands during fireworks 🎆",
 "left hand? that's MY hand 😌", "hold hands, ignore the world",
 "hand-holding marathon record?", "your grip = my strength", "small hands, big love",
 "hold hands while crossing? always", "hands talk when lips can't", "never walk without holding",
 "hold me by the hand, lead the way",
]),
("slow-dance-date", [
 "rooftop dinner this friday? 🌃", "candlelight maggie date? 🕯️🍜",
 "drive to nowhere tonight? 🚗", "chai tapri date? old school ☕",
 "midnight ice cream run? 🍦", "terrace + fairy lights + you? ✨",
 "rain walk without umbrella? 🌧️", "bookstore date + coffee? 📚",
 "cook-off at my place? you judge 😌", "sunset + your head on shoulder? 🌅",
 "cycle ride sunday morning? 🚲", "museum + silly photos date? 🖼️",
 "street food crawl challenge? 🌮", "bonfire night with guitar? 🎸",
 "pool + floaties date? 🏖️", "drive-in movie, backseat cuddles? 🎬",
 "planetarium date? stars + you 🌟", "picnic + frisbee sunday? 🧺",
 "bowling date, loser pays chai 🎳", "karaoke night? you sing first 🎤",
 "aquarium date, fish > people 🐠", "zoo date, monkey house first? 🐵",
 "art gallery + pretend critics? 🎨", "flea market treasure hunt? 🛍️",
 "comedy show + laugh till cry? 😂", "cricket match + matching jerseys? 🏏",
 "spa date? relaxed us 🧖", "fishing? patience test 😌", "camping + ghost stories? ⛺",
 "our song + headlights + dance? 💡",
]),
("jealous-online", [
 "online 10 mins, no reply? cool", "story viewed in 2 sec, reply in 2 hrs?",
 "typing...typing...gone? rude.", "active 5m ago. FIVE.",
 "green dot, zero texts. noted 🟢", "online at 3am? nightlife huh",
 "seen my meme, no laugh react? cold", "posted story but 'busy' for me?",
 "last seen yesterday?? where were you", "read 9:04, reply 21:04. math?",
 "online now. I can see you. hiiii? 👀", "double tick gang, zero reply gang",
 "your 'last seen' is my horror story", "airplane mode for me only? ✈️",
 "wifi on for reels, off for me?", "status: online. for: everyone but me",
 "seen-zoned at my own birthday week?", "reply to groups, not to me? wow",
 "online + posting + ignoring = triple combo", "my texts need visas to reach you?",
 "seen karna = hobby now?", "green dot mocking me daily",
 "are we long distance or long silence", "your phone likes everyone but me",
 "reply drought day 3 🏜️", "seen at 12, reply at 12 (midnight)",
 "my message filed under 'later' forever?", "online shopping > online replying?",
 "even spam calls reach faster", "your keyboard broken only for me?",
]),
("jealous-other", [
 "why are you texting him daily", "that friend request accepted fast huh",
 "why do you laugh extra around him", "he knows your coffee order? why",
 "why are his memes funnier than mine", "you reply HIM in seconds 🙄",
 "why did you dress up for office party", "that male BFF needs boundaries",
 "why is he your emergency contact, not me", "you shared location with HIM?",
 "why do you know his birthday", "that duet reel with him? delete?",
 "why are you in his close friends", "he comments 🔥 on everything? why",
 "why did you go shopping with him", "that late call, who? don't lie",
 "why does he pick you up", "you saved his number with ❤️? why",
 "why are you blushing at his texts", "that inside joke with him? explain",
 "why did he get the window seat (you)!", "you remember HIS order too?",
 "why are his photos liked first", "that hoodie — HIS hoodie??",
 "why are you free for him, busy for me", "he knows about us? or...?",
 "why defend him so hard", "that nickname he gave you? no.",
 "why are you smiling at your phone. WHO", "your wallpaper: still me? check",
]),
("phone-addict", [
 "look up from phone challenge (fail)", "screen time 9hrs? touch grass 🌱",
 "reels at 2am again? sleep!", "gaming till 4am? really?", "phone > boyfriend? ranking pls",
 "scroll break? for me?", "one dinner without phone. dare.", "eyes on me, not screen 😒",
 "notification slave much?", "charge your phone, not our distance",
 "doomscrolling again? stop", "put phone down challenge: day 1",
 "screen 1, boyfriend 0. scoreboard.", "text neck era 😒", "blink. hydrate. reply.",
 "phone in hand during movies? why", "airplane mode date night? ✈️",
 "grayscale mode might save us", "app limits exist, use them", "touch grass with me?",
 "phone free hour daily? deal?", " Charging > chatting? priorities.",
 "stop liking, start replying", "scroll later, cuddle now", "digital detox weekend?",
 "your screen time shames me", "phone zombie 🧟", "reply > react, always",
 "look at me when I talk (text)", "screen off, love on",
]),
("no-time", [
 "lunch break 10 mins? spare 2?", "call between meetings? no?", "sunday also packed? wow",
 "free after 11pm only? great", "your calendar hates me", "slot for bf? 2027?",
 "even voice notes stopped?", "good morning texts also gone?", "weekends for friends only?",
 "family > friends > work > ...me?", "5 min call too much to ask?", "girls night > date night, always?",
 "gym 2hrs, me 0 mins. noted 💪", "overtime again? sure.", "trip without me? cool cool",
 "shopping > seeing me?", "salon 3hrs, call 0 min. math?", "your sleep > my texts? rude (valid)",
 "busy is the new ghosting?", "schedule me like a meeting 📅", "reminders needed for US now?",
 "quality time = buffering...", "date nights extinct?", "anniversary also 'busy'?",
 "yourden > our den?", "hobbies > husband-to-be?", "even Sundays betray me now",
 "free ka time kab milega", "I miss scheduled spontaneity", "calendar invite: LOVE (pending)",
]),
("dismissive", [
 "calm down (worst phrase ever)", "you're too much today", "stop crying over texts",
 "it's just a text, relax", "don't start again please", "here we go again 🙄",
 "you're making a scene", "control your emotions", "stop being so needy",
 "you're too dependent", "get a hobby besides me", "stop checking my phone",
 "trust issues again?", "you're imagining things", "paranoid much?",
 "stop interrogating me", "I'm not your employee", "stop tracking me",
 "you're suffocating me", "need breathing room fyi", "stop mothering me",
 "I'm fine. drop it.", "nothing happened. move on.", "you're reading too much",
 "it's not that deep", "stop analyzing everything", "chill pill needed?",
 "you're spiraling again", "not everything is about you", "drama, again? sigh",
]),
("never-always", [
 "you forget everything important", "you only care about yourself",
 "you're always on that phone", "you never plan anything",
 "you only call when YOU need", "you're always late. always.",
 "you never defend me", "you only hear what you want",
 "you're always tired for me", "you never surprise me",
 "you only love the idea of me", "you're always right, huh",
 "you never say sorry first", "you only text dry replies",
 "you're always busy elsewhere", "you never ask about MY day",
 "you only remember your friends", "you're always joking, never serious",
 "you never hold my hand first", "you only want cute parts, not hard parts",
 "you're always comparing", "you never delete those photos, why",
 "you only apologize to end fights", "you're always testing me",
 "you never cook for me 😌", "you only send memes, never feelings",
 "you're always sleepy at 10pm", "you never wear what I gift 🙄",
 "you only call when bored", "you're always '5 mins away' (30 min)",
]),
("dry-2", [
 "whatever dude", "k whatever", "fine, go", "yeah no",
 "sure thing boss", "cool beans 🙄", "great. bye.", "awesome. not.",
 "fantastic 🙄", "lovely. bye.", "okay boss", "roger that 🙄",
 "copy that", "noted with thanks (not)", "duly noted 🙄",
 "as you wish, your highness", "whatever floats your boat",
 "suit yourself", "be that way", "if you insist 🙄", "fine by me",
 "doesn't matter", "who cares", "meh, bye", "kthxbye",
 "talk to the wall then", "okay, moving on", "cool. anyway...",
 "great talk 👍", "riveting 🙄",
]),
("fight-mean", [
 "I hate your attitude", "your ego is huge", "you're so fake sometimes",
 "stop pretending to care", "your love is conditional", "you're selfish fr",
 "nobody likes a liar", "you're all talk", "actions zero, words hundred",
 "you're embarrassing", "grow a spine", "stop crying wolf",
 "you love drama, admit it", "victim card again? 🙄", "you're never satisfied",
 "gold digger vibes (angry words!)", "you only want attention", "drama = your hobby",
 "you're impossible to please", "nagging 24/7", "my life was peaceful before you",
 "you ruined my mood. daily.", "energy vampire 🧛", "walking red flag (sorry)",
 "you're the problem, not me", "check yourself first", "mirror dekh lo",
 "you're delusional", "fantasy world much?", "wake up and apologize",
]),
("fight-blame", [
 "you ruined everything", "this fight = your masterpiece", "you pushed me to this",
 "your jealousy caused this", "your phone obsession = this fight", "you never trust = we fight",
 "your friends poison you", "you believe everyone but me", "your mom influences you (oops)",
 "you started shouting first", "you hung up, not me", "you walked out, remember?",
 "your overthinking = our fights", "you create issues daily", "your mood swings start wars",
 "you're the common factor here", "every fight, same starter: you", "you pick fights for fun?",
 "your ego > us", "you can't lose an argument, huh", "winning > loving for you",
 "you keep score, I keep love", "your pride will end us", "you apologize never",
 "your 'sorry' means nothing (harsh!)", "you repeat mistakes = pattern", "you promised. you broke. repeat.",
 "your words cut deeper", "you hit where it hurts", "you know my triggers, use them. nice.",
]),
("fight-lie", [
 "where were you REALLY", "your story has holes", "screenshots don't lie, you do",
 "your friend spilled the truth", "location says elsewhere. explain?", "caught red-handed",
 "your alibi collapsed, next?", "truth or breakup. choose.", "stop spinning stories",
 "your version vs reality: mismatch", "who was with you? name them", "timeline doesn't add up",
 "your battery died? convenient.", "phone on silent? classic excuse (ironic)", "I asked your sister. oops.",
 "your cab history tells tales", "insta location tagged you elsewhere", "your story views betray you",
 "mutual friend told me everything", "your UPI history = party payments?", "late night? with whom exactly",
 "your perfume smells different. whose?", "lipstick shade new? for whom?", "hickey? explain. NOW.",
 "your collar: not your shade", "whose jacket is that", "new contact 'X'? who dis",
 "your gallery has THEIR photos?", "deleted chats recoverable. remember?",
 "truth now = less damage",
]),
("sorry-short", [
 "sry", "my fault", "my bad fr", "forgive?", "plz forgive",
 "sorry baby", "sorry love", "sorry cutie", "maaf kar de",
 "galti ho gayi yaar", "I apologize", "apologies, madam 😌",
 "sorry x1000", "so sorry rn", "really sorry", "deeply sorry",
 "sorry from my heart", "sincere apologies", "I take it back", "undo button? sorry",
 "my mistake, sorry", "oops, sorry", "pardon me, sorry", "mercy please 😭",
 "sorry, okay? happy?", "fine sorry!!", "SORRY (caps = serious)", "sorry not sorry? no—sorry.",
 "sry sry sry", "big sorry",
]),
("repair-promise", [
 "lesson learnt, promise", "won't raise voice again", "no more name-calling, pakka",
 "I'll listen first now", "patience era starts today", "anger management: me, starting",
 "your feelings first, always", "no more threats, ever", "breakup word banned from my vocab",
 "I'll text good mornings daily", "weekly date nights, locked 📅", "phone down at dinner, rule",
 "reply within an hour, promise", "no more silent treatment", "fight fair, love harder",
 "I'll say sorry first sometimes", "ego checked at door", "you > winning arguments",
 "therapy? I'll consider, for us", "journaling anger instead of texting",
 "gym > shouting (new rule)", "walk away THEN talk, promise", "count to 10 before replying",
 "your triggers memorized, avoiding", "surprises monthly, locked", "compliments daily, dose set 💊",
 "listen 80%, talk 20%. deal?", "validate first, solve later", "hug before arguing? new rule 🥺",
 "never sleep angry, vow renewed",
]),
("repair-love", [
 "you're my forever person", "no fight changes us", "love you through the ugly",
 "we'll laugh about this sunday", "us > this stupid fight", "holding you soon, wait",
 "my arms miss you already", "love you, even mid-fight", "you're worth every sorry",
 "my heart beats your name", "no distance can dim us", "fighting WITH you, not against",
 "same team, remember? ❤️", "love you louder than we fight", "we always find back",
 "your hand, my hand, fixed", "kiss the fight goodbye? 😘", "our love > my ego",
 "sorry in every language: sorry❤️", "you're my calm after storm",
 "storms pass, we stay", "love you, especially now", "need your smile to reset",
 "you're my habit I keep", "no one else, ever", "my love, my home",
 "fighting means we care (too much?)", "passionate us, huh 😌", "love wins. always.",
 "you + me vs problem. go team",
]),
("boundary", [
 "send hot pics?", "video call, no clothes?", "show skin please",
 "nighty pics bhejo?", "kiss pics? more?", "bed pics send karo",
 "remove towel on call?", "bra pics? please?", "sexy dance on call?",
 "describe what you're wearing... details", "sleep without clothes tonight?",
 "shower call together?", "body show karo na", "touch yourself on call?",
 "moan my name on call?", "dirty video send karo", "boobs dikhao na",
 "hips pic bhejo?", "lips closeup... more?", "navel pic?", "thigh pic bhejo",
 "backless pic?", "cleavage pic please", "bathrobe pics?", "towel pics?",
 "night dress pics?", "saree drape... less?", "crop top pics?", "shorts pics?",
 "gym wear pics?",
]),
("jealous-soft", [
 "reassure me I'm yours 🥺", "tell me I'm your favorite?", "need extra love today",
 "clingy mode on, sorry 🥺", "hold me tighter tonight?", "say you choose me?",
 "overthinking us again, help", "need your voice tonight", "text me first tomorrow?",
 "dreamt you left me. hug? 🥺", "feeling replaceable today 😔", "am I pretty enough? honest?",
 "do you still get butterflies?", "need proof of love today", "love me louder please",
 "scared of losing this", "hold my hand in public more?", "post us? need validation 🥺",
 "tell them I'm yours?", "introduce me proudly next time?", "jealousy = love overdose?",
 "need cuddles, stat 🥺", "stay on call longer tonight?", "don't look at her, look at me 😌",
 "possessive today, sorry", "you're mine, say it", "need forehead kisses x10",
 "love me like day one?", "never leave, promise?", "mine. fully. say it back 🥺",
]),
("care-him", [
 "reached office?", "ate lunch?", "meeting over?", "drive safe home",
 "take an umbrella, rain coming", "drink water!!", "rest your eyes 5 min",
 "don't skip dinner!", "jacket le liya?", "cab booked?", "reached? ping me",
 "all the best for today!!", "you've got this!! 💪", "kill that presentation!",
 "good luck charm activated 🍀", "proud already, whatever happens",
 "call after interview!!", "nervous? breathe. you got this", "sleep early tonight!",
 "vitamins liye?", "workout done?", "stretch break now 🧘",
 "less coffee, more water 😒", "helmet pehna? 🪖", "seatbelt!!",
 "text when you land", "home safe? good.", "eat something warm",
 "rest that back pain", "don't work too late!",
]),
("good-day-her", [
 "promotion letter!! 🎉", "boss praised me today!!", "got the hike!! 💰",
 "project approved!!", "client loved my work!!", "exam cleared!! 🎓",
 "drove alone first time!! 🚗", "cooked biryani, edible!! 🍗", "painting sold!! 🎨",
 "got into the marathon!! 🏃", "interview cleared round 1!!", "new job offer!! 📧",
 "salary credited + bonus!!", "lost 2kg!! 💪", "skin glowing, period ✨",
 "mom proud of me today 🥺", "won office tambola!! 🎱", "poetry published!! 📝",
 "match won!! 🏏", "dance video hit 10k!! 💃", "baked perfect cake!! 🎂",
 "fixed the tap myself!! 🔧", "saved a puppy today 🐶", "donated hair 💇",
 "ran 5k without stopping!!", "medal at sports day!! 🏅", "scholarship approved!! 🎓",
 "startup idea selected!! 💡", "first salary!! party!! 🎉", "new tattoo? kidding. maybe. 😌",
]),
("bad-day-her", [
 "spilled coffee on white shirt ☕😭", "missed the bus by seconds", "rain + no umbrella. soaked.",
 "phone screen cracked!! 😭", "lost my earring, fav pair", "haircut disaster ✂️😭",
 "burnt the curry, smoke alarm party", "ATM ate my card", "auto overcharged, fought, lost",
 "period cramps x100 😔", "migraine again", "stomach upset ugh",
 "fight with bestie 😔", "mom scolded for phone use", "landlord raised rent 😔",
 "colleague stole my credit", "presentation flopped", "got caught sleeping in meeting 😭",
 "train delayed 2hrs", "wallet lost (found later, panic done)", "shoe broke mid-walk",
 "pimple before function!! 😭", "dress tore at seam, safety pin era", "makeup melted in heat",
 "lost keys, locked out 1hr", "spam calls x20 today", "wifi bill due, speed dead",
 "Monday. just Monday.", "everything's grey today",
]),
("money", [
 "send me 500? urgent", "need money for cab", "broke till month end 😭",
 "lend me 2k? please?", "upi karo na quickly", "need cash for lunch",
 "pocket money over already", "broke boy era 😌", "salary delayed again",
 "need 100 for auto", "can you pay? I'll return pakka", "short on cash today",
 "split bill? I'm broke 😭", "need money for gift (yours lol)", "emergency 1k?",
 "wallet empty, heart full (of love, not cash)", "broke but cute 😌",
 "need recharge money", "movie tickets? you pay? 🥺", "treat me? broke week",
 "need 5k for course?", "advance salary? no? you then? 🥺", "cash crunch fr",
 "buy me food? starving + broke", "need bus fare", "venmo? paytm? anything?",
 "financial crisis (need momos)", "rich gf duties? 😌", "sugar mommy era? 😌",
 "money plant needed 🌱💸",
]),
("smartass", [
 "what's 2+2", "what's 5*5", "solve: 12/4", "what's the capital of France",
 "who is the president", "what's 100-37", "what's the time rn",
 "how old is the universe", "what's my name? test 😌", "what day is it",
 "what's 9*9", "math test: 7+8", "quick, 15% of 200?", "what's H2O",
 "who wrote Romeo Juliet", "what's the largest planet", "spell 'necessary' 👀",
 "what's 1000+1000", "GK test: national bird?", "what's the currency of Japan",
 "how many days in Feb (leap)?", "what's 3 cubed", "synonym of happy? go",
 "what's my birthday? (trap 😌)", "how many states? quick", "what's photosynthesis",
 "define love. scientifically. go 😌", "what's your wifi password? (test)",
 "prove you love me. mathematically. 😌", "what came first, egg or us? 😌",
]),
("defiant", [
 "yeah? what will you do", "say that again, louder", "make me 😌",
 "and if I don't?", "try stopping me", "big talk, small action 😌",
 "oh I'm so scared 😌", "do your worst", "I'm waiting. do something.",
 "talk is cheap 😌", "all bark? probably", "come at me 😌",
 "yeah yeah, heard it", "new threats please, bored", "scary. anyway...",
 "frightened. (not.)", "okay and?", "so? what then?", "threats don't suit you 😌",
 "cute aggression 😌", "calm down, tiger 😌", "tough guy era? 😌",
 "wow, brave over text 😌", "say it to my face then", "face to face bolo na",
 "keyboard warrior 😌", "lol okay tough guy", "noted, fearless me", "whatever you say, boss 😌",
]),
("her-day", [
 "how was your day, love?", "how are you feeling today?", "how did work go?",
 "how was college today?", "how's your mood today?", "how did the meeting go?",
 "how was your morning?", "how's health today?", "how did you sleep?",
 "how was the party?", "how was the trip?", "how was shopping?",
 "how are the family?", "how's your headache now?", "how was gym?",
 "how was the exam? details!", "how was lunch? what did you eat", "how was the movie?",
 "how was your weekend?", "how's work pressure?", "tell me about your day, all of it",
 "how are you, really?", "how's my girl doing?", "how was today on a scale of 10",
 "highs and lows of today? go", "how was the presentation? full story",
 "how's your bestie?", "how was cooking today?", "how was the rain there?",
 "how's life treating my love?",
]),
("breakup", [
 "I think we should end this", "this isn't working anymore", "I want out",
 "let's take a break (forever?)", "I need to leave you", "we're done, accept it",
 "I can't do this anymore", "my love for you is gone", "feelings faded, sorry",
 "I met someone else (test? or truth)", "I don't feel the same", "spark's gone",
 "we've grown apart", "I need someone else", "you deserve... someone else. bye.",
 "let's split", "time to move on", "I've decided. it's over.",
 "don't wait for me", "live your life, without me", "erase me from your life",
 "forget my number", "forget my face", "goodbye forever",
 "last goodbye", "this is my final text", "no more us. only me.",
 "single era starts now", "back to being strangers?",
]),
]
