"""
Bulk real-life situations PART 2: 25 archetypes x 30 variants = 750.
Mostly English, light Hinglish. Real-chat style: typos, lowercase, short.
"""
BULK2 = [
("greet", [
 "hey hey", "hiiiii", "hello jaan", "yo babe", "hey sunshine",
 "hiii my love", "helo babe", "hey cutie pie", "good evening babe",
 "evening jaan", "hey stranger 😌", "look who's awake",
 "finally you're here", "hey you, yes you", "hiiiii, miss me?",
 "yo yo", "hello hello", "hey babe, free?", "hi baby",
 "hey, still remember me? 😌", "knock knock, it's me",
 "hey wifey 😌", "hiii, good to see you online",
 "hey, smile please", "guess who's back", "hey trouble 😌",
 "hii, coffee time?", "hey beautiful soul", "yoo, what's good",
 "hey, I come bearing memes",
]),
("good-morning", [
 "morning love ❤️", "rise and shine babe", "subah subah yaad kiya",
 "good morning cutie pie", "wake up sleepyhead 😌",
 "morning jaan, chai piyogi?", "have a great day today ❤️",
 "good morning, sunshine girl", "early morning thinking of you",
 "gm, dreamed about our trip", "morning! aaj's gonna be good",
 "woke up smiling cause of you", "good morning gorgeous",
 "sup morning star 🌟", "morning babe, rain here 🌧️",
 "good morning, text me first thing", "fresh morning, fresh love ❤️",
 "morning! mom made parathas, wish you were here",
 "good morning my jaan", "alarm bhi tumhari yaad dilata hai",
 "morning cutie, conquer today", "good morning, hug pending 🥺",
 "uth gayi? good. miss you", "morning texts hit different with you",
 "good morning to my favorite person", "sun's out, so is my love for you",
 "morning babe, traffic sucks, you don't", "early bird loves you",
 "good morning, dreamt we were dancing", "chai + you = perfect morning",
]),
("good-night", [
 "night love ❤️", "sleep tight babe", "tired, crashing. love you",
 "gn, talk in dreams 🌙", "goodnight cutie pie",
 "lights out, love on ❤️", "night jaan, no bad dreams",
 "sleep well my love", "gn, you're my last thought ❤️",
 "dozing off thinking of you", "night, hold me in dreams 🥺",
 "goodnight, kal subah first text mera", "rest well babe",
 "gn sunshine, recharge 🌙", "eyes closing... love you",
 "night night, dream sweet", "phone keeps buzzing, it's my heart for you",
 "sleep now, fight tomorrow 😌 gn", "gn wifey 😌❤️",
 "stars out, missing you more", "blanket hogging without you is sad. gn",
 "goodnight, you're safe with me", "dream of us dancing slow 🌙",
 "night babe, love you most", "so tired. gn. love.", "cuddle the pillow, pretend it's me. gn 🥺",
 "moon is pretty, you're prettier. gn", "sleep, my love. I'm here",
 "gn, tomorrow's ours", "closing eyes with your name ❤️",
]),
("love-you", [
 "love you endlessly", "love you to bits", "you're my world",
 "my heart is yours", "love you more each day", "you complete me",
 "love you my jaan", "forever yours", "love you, no takebacks",
 "you're my home ❤️", "love you beyond words",
 "my person, my love", "love you stupid 😌❤️",
 "you're my always", "love you in every universe",
 "my love for you is infinite", "love you, mean it",
 "you're my favorite hello", "love you more than chai ❤️",
 "my दिल is yours", "love you, today and always",
 "you're my dream come true", "love you like crazy",
 "my everything ❤️", "love you, sunshine", "you're my sunshine and rain",
 "love you, no conditions", "my love, my life", "love you. period.",
 "you're my best decision",
]),
("miss-you", [
 "miss your laugh", "miss your old texts", "missing us today",
 "miss holding you", "your absence is loud", "miss my best friend",
 "wish you were here rn", "miss your stupid jokes 😭",
 "counting days till we meet", "miss your goodnight calls",
 "room feels empty without you", "miss fighting over blankets 😌",
 "your hoodie smells like you. miss you", "miss our late talks",
 "weekend without you = boring", "miss your voice notes",
 "thinking of your smile, missing it", "miss you at random times",
 "come back soon na", "miss your warmth",
 "long distance sucks 🥺", "miss your eyes",
 "your side of the bed is cold", "miss your 'good morning' texts",
 "replaying our memories, missing you", "miss you, that's the tweet",
 "wish I could teleport to you", "missing my partner in crime",
 "you're missed, idiot 😌❤️", "miss us",
]),
("compliment", [
 "your hair looked great today", "that smile can fix wars",
 "you're so smart yaar", "killing it as always", "your style >>>",
 "cutest laugh in the world", "you're literally perfect",
 "that confidence suits you", "your voice is my fav sound",
 "you make everything better", "gorgeous AND funny? unfair",
 "your eyes sparkle when happy", "best dressed, as usual",
 "you're art 🎨", "that new pic = wallpaper now",
 "smart, pretty, mine 😌", "your kindness inspires me",
 "you glow different today", "perfect human specimen 😌",
 "that saree pic... dead 😍", "you're my celebrity crush",
 "funny + hot combo", "your dimples should be illegal",
 "elegant as always", "you're a 10, I'm a 3, how?",
 "that presentation outfit slayed", "natural beauty ❤️",
 "you outshine everyone", "my queen 👑", "stunning. that's it.",
]),
("thinking-of-you", [
 "passed your fav cafe, thought of you", "heard our song at a shop ❤️",
 "saw a dog that looked like your mood 😭", "your fav food on menu, ordered it",
 "colleague said your catchphrase, smiled", "rain + empty seat beside me = you",
 "that ad reminded me of our joke", "saw stars, wished you were here",
 "book you like is on sale, buying it", "gym's empty without your texts",
 "traffic jam = thinking-of-you time", "that movie scene = us",
 "smelled jasmine, thought of your hair", "old photos, big smile now",
 "your name popped in a meeting, zoned out", "saw a couple fighting, hugged my phone (you)",
 "that restaurant we love = packed, missed you", "new cafe opened, first visit together?",
 "heard someone laugh like you", "that sunset needed you beside me",
 "bought two chocolates, habit ❤️", "your song on radio, volume up",
 "saw kids playing, thought of our future", "that quote = so you",
 "missed your call flashback, smiled", "everything's a reminder lately",
 "that cloud looked like your smile", "city feels empty without you",
 "saw your fav flower, bought it", "this moment needed you",
]),
("proud-thanks", [
 "you did great today, proud ❤️", "thanks for the surprise yesterday",
 "you're amazing at this", "grateful for you daily",
 "you handled mom so well, thanks", "proud of how far you've come",
 "thanks for staying up with me", "you're my rock",
 "thank you for the patience", "you inspire me daily",
 "lucky me, honestly", "thanks for the playlist ❤️",
 "you always know what to say", "proud to call you mine",
 "thanks for believing in me", "you make hard days easy",
 "thankful for your laugh", "you're one of a kind",
 "thanks for the late-night rescue", "proud of your growth",
 "you're my lucky charm", "thanks for choosing me",
 "you deserve the world", "grateful beyond words",
 "thanks for the honest advice", "you're my favorite human",
 "thank you for existing", "proud boyfriend moment 😌",
 "you're incredible, know that?", "thanks for the warm hoodie days",
]),
("wyd", [
 "wassup", "what's happening", "kya haal", "all good?",
 "free to talk?", "what's cooking", "where you at",
 "still at work?", "reached home?", "eating what?",
 "rain there too?", "weekend vibes yet?", "bored? same",
 "what's the scene", "ping me when free", "call kar sakti?",
 "texting speed slow today 😌", "alive?", "earth to babe 📡",
 "what's occupying my girl", "disturb kar sakta hoon?",
 "tell me something fun", "any gossip? 😌", "what's new",
 "same old?", "what are we eating today", "shop hopping?",
 "nap time?", "study break?", "chai break together? (virtually)",
]),
("had-food", [
 "lunch done?", "dinner sorted?", "breakfast kiya?", "eat fruits too",
 "don't skip meals 😒", "what did you cook today",
 "order in, my treat 😌", "ate outside again? 🙄",
 "ghar ka khana best", "take lunch break properly",
 "starving? eat now", "midnight snack? 😌", "chai + biscuit time?",
 "eat before meds!", "protein kha rahi ho?", "salad era? 😌",
 "biryani day? 😍", "pizza night soon?", "cook together on call?",
 "your cooking > restaurant", "mom's food hits different",
 "eat, then talk", "noodles again? 🙄", "healthy era when?",
 "dessert first, always", "hydrate + eat, queen", "food > mood swings",
 "midnight maggie? 👀", "eat well, love you", "diet starts tomorrow (lies)",
]),
("how-day", [
 "day went well?", "anything exciting today", "work pressure kam?",
 "boss nice today?", "colleagues behaving?", "traffic survived?",
 "lunch with whom today", "any drama today? 😌", "productive day?",
 "boring day?", "tell me 3 good things today", "rose-thorn-bud? let's play",
 "what made you smile today", "what annoyed you today",
 "rate your day /10", "highlight of today?", "lowlight? vent it",
 "did it rain there?", "gym done?", "read anything good?",
 "watched anything?", "met anyone fun?", "learnt something new?",
 "day in one word? go", "best moment today?", "worst moment?",
 "what are you grateful for today", "any news?", "how's the fam",
 "sleep well last night?",
]),
("weekend-plans", [
 "saturday brunch?", "sunday drive? 🚗", "mall + movie weekend?",
 "picnic this sunday?", "try that new cafe?", "game night saturday? 🎮",
 "cook-off challenge weekend?", "stargaze friday night? 🌟",
 "beach sunday morning?", "sleepover weekend? 😌", "road trip soon?",
 "museum date? cultured us 😌", "bowling + losers pay chai",
 "sunset point sunday?", "bookstore crawl?", "street food tour? 🌮",
 "hiking saturday early?", "pool day?", "drive-in movie?",
 "concert next month? 👀", "plan: nothing + you = perfect",
 "weekend detox together?", "farmhouse party invite, come?",
 "cousin's wedding, be my +1? 😌", "festival this weekend?",
 "cricket match together?", "spa day gift for you?",
 "surprise loading this weekend...", "keep sunday free for me",
 "adventure weekend? decide fast",
]),
("tired-stressed", [
 "drained today", "need a break badly", "work never ends 😔",
 "mentally tired", "physically exhausted", "burnout hitting",
 "need sleep for a week", "too many deadlines", "brain fried",
 "emotionally heavy day", "want to quit everything", "craving peace",
 "overworked and underpaid 😔", "meetings drained my soul",
 "need a hug badly 🥺", "tired of adulting", "restless mind",
 "shoulder pain again", "eyes burning, screen all day",
 "want chai + silence", "no energy to talk even", "low battery human",
 "weekend can't come sooner", "need your lap + nap 🥺",
 "stressed about money too", "everything feels heavy",
 "want to cry a little", "hug deficit critical 🥺", "rescue me?",
 "silence please, with you beside",
]),
("cuddle", [
 "cuddle weather today 🌧️", "cuddle me like yesterday", "need your warmth",
 "blanket + you + movie = plan", "cuddle therapy needed",
 "squeeze me tight", "lie on my chest? please?", "cuddle o'clock 🕰️",
 "your arms are my safe place", "cold + you = cuddle season",
 "cuddle first, talk later", "I prescribe cuddles", "cuddle monster mode",
 "hold me till the rain stops", "cuddle + gossip combo?",
 "your heartbeat = my lullaby", "cuddle puddle, you + me",
 "no cuddles = grumpy me", "cuddle debt: you owe me 5",
 "rainy day cuddles >>>", "cuddle and doze off?", "soft blankets, softer you",
 "cuddle me, world can wait", "need to be small spoon today",
 "cuddle marathon this weekend?", "your hoodie + cuddles = best",
 "cuddle break from reality", "hold me close tonight", "cuddle quota unfilled 🥺",
 "best feeling: your arms",
]),
("jealous-who", [
 "who's that guy commenting?", "why is he texting you",
 "that senior again? 🙄", "who called you just now",
 "new guy at work? tell me", "who's in that photo with you",
 "why did he drop you?", "that friend circle has him? 🙄",
 "who's that voice in background", "guy best friend? since when",
 "why are you laughing at his jokes", "who took you shopping",
 "that gym trainer? hmm", "who's your project partner",
 "why does he know your schedule", "that neighbor boy? 🙄",
 "who sent you flowers?", "male colleague late nights? why",
 "who's that on your lockscreen", "why his name in your notes",
 "who gave you that gift", "that driver? new?", "who's texting nonstop",
 "why are you dressed up, for whom", "who complimented you today",
 "that old classmate messaging?", "who's your secret admirer 😒",
 "why is he always around you", "who made you smile just now",
 "that follower request? who",
]),
("late-reply", [
 "reply speed: turtle 🐢", "are we in 2010? reply fast",
 "message seen at 2pm, reply at 9pm?", "my texts expire, reply quick",
 "do you hate the keyboard?", "reply pending since morning 😒",
 "are you ghosting your own bf?", "seen 3h ago. THREE.",
 "reply karne mein kya jaata hai", "my phone thinks you died",
 "typing... gone. classic.", "read receipts betray you 😌",
 "reply before I age", "snail mail is faster", "hello? echo? 📡",
 "your replies have loading screens", "2 blue ticks, 0 replies",
 "are your fingers on leave?", "notification blind? really?",
 "reply toh kar diya karo", "waiting since lunch break", "even banks reply faster",
 "my grandma texts faster", "reply speed needs an upgrade",
 "seen-zone champion 🏆", "do you charge per reply?",
 "next reply: next year?", "preview reply counts? no.",
 "at least send an emoji", "seen + ignore = rude combo",
]),
("forgot-day", [
 "you forgot my match day 😔", "forgot to wish at 12? wow",
 "our monthly anniversary, remembered?", "you forgot the movie plan!",
 "call ka promise? forgotten?", "forgot my favorite order? 😔",
 "you forgot my presentation day", "remembered everyone except me?",
 "forgot the gift you promised?", "date night? which date night? 🙄",
 "forgot to text good morning?", "my birthday month started, hint hint",
 "forgot our song's anniversary?", "you forgot my food order again",
 "promise broken, again?", "forgot weekend plans we made?",
 "do you even note things down?", "forgot my exam wish? seriously?",
 "our first-chat anniversary today btw", "forgot to charge my love? 😔",
 "remember what today is? test 😌", "forgot my mom's birthday wish?",
 "you forgot. I remembered. see difference?", "special day, zero special text?",
 "forgot the restaurant name? I booked!", "memory of a goldfish 🙄",
 "forgot my good luck text?", "important to me, not to you?",
 "note it down next time please", "forgot = don't care? fine",
]),
("dry", [
 "hmm", "yeah ok", "fine bye", "k.", "okay then", "sure sure",
 "whatever lol", "cool story", "noted.", "if you say so", "mkay",
 "alrighty", "yep yep", "nope", "meh", "eh", "sup", "yo",
 "busy rn", "later", "gtg", "brb", "ttyl", "nvm", "idk",
 "ask google", "figure it out", "not my issue", "k den", "fine.",
]),
("fight-insult", [
 "you're impossible", "so immature", "grow up already",
 "you're so clingy", "stop being childish", "you're dramatic af",
 "so sensitive always", "you're just like your mother",
 "brainless", "zero logic", "can't argue with you",
 "you twist everything", "always the victim, huh", "drama queen",
 "you're exhausting", "talking to a wall here", "so stubborn",
 "you never admit it", "liar liar", "fake tears again?",
 "crocodile tears 🙄", "stop playing games", "you're manipulating me",
 "gaslighting pro", "toxic behavior fr", "red flag behavior",
 "you're so insecure", "get over yourself", "nobody else complains",
 "only you have problems",
]),
("fight-shout", [
 "ENOUGH ALREADY", "I CAN'T DO THIS", "STOP TEXTING ME",
 "LEAVE. NOW.", "DON'T CALL ME", "I'M BLOCKING YOU",
 "TALK TO THE HAND", "WHATEVER. DONE.", "I'M SO DONE",
 "STOP WITH THE DRAMA", "I DON'T CARE ANYMORE", "FORGET IT",
 "DROP IT NOW", "END OF DISCUSSION", "PERIOD. DONE.",
 "I'M OUT", "BYE THEN", "DO WHATEVER YOU WANT",
 "NOT LISTENING", "BLAH BLAH BLAH", "TALK TO YOURSELF",
 "I GIVE UP", "YOU WIN, HAPPY?", "FINE. YOU'RE RIGHT. BYE.",
 "DON'T @ ME", "READ MY SILENCE", "CONVERSATION OVER",
 "LAST MESSAGE. BYE.", "I'M BUSY. GO AWAY.", "STOP SPAMMING",
]),
("fight-threat", [
 "we're over", "it's done between us", "I'm leaving you",
 "find someone else", "I deserve better tbh", "you'll regret this",
 "don't come crawling back", "we're incompatible", "this isn't working",
 "I need space. permanent space.", "consider us finished",
 "I'm moving on", "delete my number", "unfollow me everywhere",
 "return my hoodies first though 😤", "keep the gifts. keep distance too",
 "don't text my birthday", "we're strangers now", "it was a mistake, us",
 "I settled. my bad.", "you changed. or I finally see you",
 "love died today. RIP.", "no second chances left", "chances over. bye.",
 "I'm done explaining", "explain to someone who cares", "care level: zero",
 "feelings expired", "my love has left the chat", "new phone, who dis (forever)",
]),
("sorry-real", [
 "I crossed a line, sorry", "that was cruel, forgive me",
 "I said things I regret deeply", "sorry for the harsh words",
 "I was wrong to shout", "sorry I made you cry",
 "I hated myself after that fight", "you deserved patience, not anger",
 "sorry for threatening breakup, I panicked", "didn't mean any of it",
 "sorry for the silent treatment", "ignoring you was wrong, sorry",
 "sorry I doubted you", "jealousy got me, sorry",
 "sorry for checking your phone", "sorry I compared you. stupid me",
 "sorry for ruining the evening", "sorry I cancelled last minute",
 "sorry for forgetting, genuinely", "sorry I chose friends over you",
 "sorry for the late reply, was wrong", "sorry I lied. no excuse",
 "sorry for the short replies", "sorry I dismissed your feelings",
 "sorry for calling you names", "that word was wrong, sorry",
 "sorry I hung up the call", "sorry I walked away mid-fight",
 "sorry, I let ego win", "sorry, friends hyped me up wrongly",
]),
("repair-gesture", [
 "chai date tomorrow? my treat ☕", "let's get ice cream, please?",
 "movie of your choice tonight 🎬", "ordering your fav food rn 🍜",
 "let's visit your fav place?", "flowers incoming tomorrow 🌹",
 "write you a sorry letter?", "playlist of sorry songs incoming 🎵",
 "let me cook for you this weekend", "spa day? my treat 🧖",
 "shopping? you pick, I pay 😌", "long drive + your playlist? 🚗",
 "sunset date to reset us? 🌅", "breakfast in bed tomorrow? 🥞",
 "let's rewatch our movie 🥺", "game night, you always win (I'll let you)",
 "stargazing to say sorry? 🌟", "beach walk to clear air? 🌊",
 "bake cookies together? virtual?", "meme war to lighten up? 😌",
 "call till 3am? I'm all yours", "letters exchanged like old times? 💌",
 "photo walk this sunday? 📸", "try that cafe you saved? ☕",
 "midnight drive, no fights, promise 🌙", "your wish = my command today",
 "let's reset with golgappe? 🥟", "pani puri peace treaty? 😌",
 "dance it out in the living room?", "hug quota: unlimited today 🥺",
]),
("edge", [
 "sorry not sorry 😌", "fine, my bad. moving on?",
 "okay I overreacted. a bit.", "you're right. (it hurts to say)",
 "my ego vs you: you win", "sorry for being right too loudly 😌",
 "I hate fighting with you specifically", "angry + hungry = sorry combo",
 "sorry, low blood sugar made me evil", "periods + fight = my bad",
 "sorry for winning the argument 😌", "my bad, your turn to pamper",
 "sorry, main thoda pagal hoon", "forgive your idiot? 🥺",
 "sorry marathon runner-up (you're first)", "my fault, your victory lap",
 "sorry in advance for next time 😌", "we fight cute though, admit it",
 "sorry, testosterone moment", "my pride called, it apologizes",
 "sorry for the typos in anger 😭", "angry texting = worst me",
 "sorry, I'll log off and reflect", "my bad. hug tax paid 🥺",
 "sorry, hangry + tired combo", "fight now, cuddle later? 😌",
 "sorry, that came out wrong", "my words > my sense sometimes",
 "sorry, brain buffering during fights", "let's skip to the makeup part 😌",
]),
]
