"""
Bulk real-life situations: (tag, [boyfriend messages]).
~45 archetypes x 10 variants ≈ 450 + the 68 core = ~518 training episodes.
Written like real chats: typos, lowercase, slang, Hinglish mix.
bulk_train.py interleaves them round-robin so mood arcs stay realistic.
"""

BULK = [
("greet", [
 "hey", "hiii", "heyy babe", "yo", "hello beautiful", "hii jaan",
 "hey you", "helooo", "hiii cutie", "hey are you there",
]),
("good-morning", [
 "good morning babe ❤️", "gm beautiful", "morning jaan, uth gayi?",
 "good morningg, had tea?", "subah ho gayi, msg kar diya 😌",
 "gm ❤️ dreamed of you", "morning cutie, aaj ka plan kya hai",
 "good morning my love", "utho, office ka time 😌",
 "gm babe, miss you already",
]),
("good-night", [
 "good night babe ❤️", "gn jaan, sweet dreams", "so jaa, kal baat karte hain",
 "night night, dream of me 😌", "goodnight my love 🌙",
 "neend aa rahi, gn ❤️", "so ja, phone rakh de 😌 gn",
 "gn cutie, love you", "good night, kal milte hain?",
 "sweet dreams babe, I love you",
]),
("love-you", [
 "I love you", "love you so much babe", "love u jaan ❤️",
 "pyar karta hoon tumse", "I love you more than yesterday",
 "love you to the moon", "tum meri ho, samjhi? ❤️",
 "I love you idiot 😌❤️", "love you love you love you",
 "I love you, kabhi mat jaana",
]),
("miss-you", [
 "miss you", "miss you so much 🥺", "yaad aa rahi hai",
 "miss you babe, kab miloge", "I miss your voice",
 "bohot miss kar raha hoon", "miss you, call karein?",
 "tumhari yaad aa rahi hai 🥺", "miss you like crazy",
 "ghar khaali lag raha hai without you",
]),
("compliment", [
 "you look gorgeous today", "that dress pic... wow 😍",
 "you're so cute yaar", "tumhari smile best hai",
 "that laugh of yours ❤️", "you looked amazing in that reel",
 "cute + smart + mine. jackpot 😌", "your eyes... uff",
 "that photo broke my heart (good way) 🥺",
 "you're glowing today, kya baat",
]),
("thinking-of-you", [
 "just thought of you randomly 🥺", "this song reminded me of you",
 "saw a couple holding hands, thought of us", "you crossed my mind mid-meeting 😌",
 "this meme is so you 😭", "chai pee raha tha, yaad aa gayi",
 "your fav song came on shuffle ❤️", "saw flowers, thought of you",
 "everything reminds me of you these days", "2:47pm, boring day, thinking of you",
]),
("proud-thanks", [
 "proud of you for today ❤️", "you handled that so well, proud",
 "thanks for yesterday, seriously", "thank you for being you",
 "you're the best thing in my life", "lucky to have you yaar",
 "thanks for listening last night 🥺", "you always show up. thank you",
 "I brag about you to everyone 😌", "you make me want to be better",
]),
("future-talk", [
 "can't wait to marry you 💍", "our future house will have a terrace",
 "imagine us old together 😌", "you + me + forever. deal?",
 "we'll travel the world together", "someday: you, me, our kitchen fights 😌",
 "I want a life with you in it", "future Mrs. me 😌💍",
 "we'll laugh about these days later", "growing old with you sounds perfect",
]),
("surprise-plan", [
 "surprise dinner friday, be ready 😌", "got you something, guess what",
 "wear something nice tomorrow evening", "closed your eyes? surprise coming",
 "flowers + chocolate on the way 🌹", "packed a picnic, terrace 6pm?",
 "movie tickets booked, just us 🎬", "small gift, big love. check your door",
 "cancelled everything saturday. you're mine", "surprise call in 10 mins 😌",
]),
("wyd", [
 "wyd", "what are you doing", "kya kar rahi ho",
 "wru, what are you upto", "hey what you doing rn",
 "busy? ya free ho", "kya chal raha hai", "whats up babe",
 "are you free rn", "doing what?",
]),
("had-food", [
 "did you eat?", "khana khaya?", "lunch kiya?",
 "dinner kar liya?", "kha lo time pe 😒", "had your chai?",
 "eat something na, please", "maggie kha rahi ho ya khana? 😌",
 "dinner done? tell me", "bhook lagi hogi, kha lo",
]),
("how-day", [
 "how was your day", "aaj ka din kaisa tha", "how did the exam go",
 "how was the interview??", "presentation kaisa gaya",
 "how was work today", "day kaisa tha babe", "tell me about your day 🥺",
 "everything okay today?", "how are you feeling today",
]),
("weekend-plans", [
 "weekend pe kya plan", "saturday free ho?", "sunday milte hain?",
 "what are we doing this weekend", "friday night plans? 😌",
 "long drive sunday? 🚗", "movie sunday? you pick",
 "weekend = you + me. final 😌", "terrace night saturday?",
 "ice cream walk sunday evening?",
]),
("small-talk", [
 "guess what happened today", "you won't believe this 😭",
 "saw the funniest dog today", "it rained here, thought of you 🌧️",
 "tried cooking, almost died 😭", "new song dropped, listen rn",
 "had the weirdest dream about us", "my mom asked about you 😌",
 "cricket dekh rahi ho?", "match dekhte hain saath mein?",
]),
("tired-stressed", [
 "so tired yaar", "exhausted, long day", "bohot tension hai office mein",
 "head is bursting", "bad day today 😔", "feeling low babe",
 "boss shouted again", "can't sleep, overthinking", "neend nahi aa rahi",
 "sad for no reason today",
]),
("exam-fear", [
 "exam kal hai, darr lag raha", "syllabus khatam nahi hua 😭",
 "interview tomorrow, wish me luck", "presentation hai, nervous hoon",
 "fail ho jaunga lagta hai", "padhai nahi ho rahi, help",
 "all-nighter tonight 😔", "result aane wala hai, scared",
 "mock test mein kam aaye", "placement season stress 😔",
]),
("cuddle", [
 "cuddle karna hai", "come cuddle me", "need cuddles rn 🥺",
 "cuddle + movie tonight?", "your arms. now. 🥺",
 "can we just lie together quietly", "hug me tight na",
 "cuddle pause on life 🥺", "I need to be held",
 "cuddles fix everything, science 🥺",
]),
("kiss-hug", [
 "kiss me 😘", "one kiss please", "forehead kiss dedo 🥺",
 "hug me from behind", "ghadi bhar hug?", "kiss on call? 😘",
 "send a flying kiss", "hug break needed", "tight hug, long time 🥺",
 "kiss me like you mean it 😌",
]),
("hold-hands", [
 "hold my hand", "haath pakdo na", "walking hand in hand soon?",
 "don't let go of my hand", "your hand fits mine perfectly",
 "hold my hand through the crowd", "pocket mein haath daal lo 😌",
 "interlocked fingers >>>", "haath thaam ke chalna hai",
 "your cold hands, my pockets 😌",
]),
("slow-dance-date", [
 "slow dance with me tonight?", "living room, our song, you + me 🥺",
 "long drive tonight? 🚗🌙", "terrace pe chai? just us",
 "stargazing chalenge?", "beach evening soon? 🌊",
 "ice cream walk? my treat 😌", "midnight maggie date? 🍜",
 "hoodie dedo, it's cold 🥺", "fall asleep on call with me? 🌙",
]),
("jealous-who", [
 "who was that guy?", "who were you laughing with at the party",
 "kaun tha woh ladka?", "why were you with him so long",
 "who's that new follower?", "who texted you at 1am?",
 "that guy from college again?", "who dropped you home?",
 "us ladke se kya baat kar rahi thi", "who's he to you exactly",
]),
("jealous-online", [
 "online thi, reply kyun nahi kiya", "seen karke gayab? nice",
 "2am online? kaun tha?", "last seen 3am?? explain",
 "typing... then stopped? bolo na", "blue ticks, no reply. wow",
 "active now but ignoring me?", "online ho, baat nahi karni?",
 "story dekhi, reply nahi? okay", "kabse online ho, busy with whom",
]),
("jealous-other", [
 "don't talk to your ex", "why did you like his photo",
 "why are you following him", "that coworker again? 🙄",
 "stop laughing with other guys", "unfollow him na please",
 "why does HE comment on everything", "you looked too happy with them",
 "don't go to that party without me", "I don't like that friend of yours",
]),
("late-reply", [
 "reply late kyun karti ho", "3 ghante baad reply? seriously?",
 "seen pe chhod diya", "itna late? busy thi ya ignore?",
 "message kal ka tha, reply aaj?", "typing dikha phir gayab",
 "reply karne mein tax lagta hai?", "do din se seen zone 😒",
 "urgent tha yaar, phir bhi late", "phone haath mein hi hota hai na",
]),
("phone-addict", [
 "phone rakh do na please", "reels > me? okay 🙄",
 "dinner pe bhi phone?", "game khatam? ya main jaun?",
 "you're always on instagram", "baat karte karte scroll? wow",
 "phone se shaadi kar lo 😒", "ek ghante se game mein ho",
 "status daal diya, reply nahi? nice", "screen time kam karo na",
]),
("forgot-day", [
 "anniversary bhool gaye?", "mera birthday yaad hai?", "you forgot our date!!",
 "promise kiya tha, bhool gaye", "kal ka plan yaad hai ya nahi",
 "you forgot to call again", "important day tha aaj 😔",
 "yaad tha na? ya main hi pagal hoon", "ek date yaad nahi rehti",
 "you forgot. again. wow.",
]),
("no-time", [
 "time hi nahi hai tumhare paas", "friends > me, always",
 "ek call ke liye time nahi?", "weekend bhi busy? great",
 "priority list mein kahan hoon?", "5 min nahi nikaal sakte?",
 "kaam kaam kaam. bas.", "doston ke saath time, mere liye nahi",
 "you're never free anymore", "kab miloge? next year?",
]),
("dismissive", [
 "chill out yaar", "itna bada deal nahi hai", "overreact mat karo",
 "drama band karo", "you're overthinking", "rona band karo na",
 "itna sensitive kyun ho", "baat ko kheench mat", "jaane do na, move on",
 "tum hamesha aise hi karti ho",
]),
("never-always", [
 "you never listen to me", "tum kabhi samajhti nahi",
 "you always do this", "har baar yahi hota hai",
 "you never have time", "tumhe kabhi farak nahi padta",
 "you always pick fights", "har cheez mein problem",
 "you never apologize first", "tum kabhi nahi badlogi",
]),
("dry", [
 "ok", "k", "fine", "hmm", "yeah", "cool", "sure", "whatever",
 "seen", "lol",
]),
("dry-2", [
 "hmm okay", "fine whatever", "yeah sure", "k bye", "ok cool",
 "whatever you say", "as you wish", "do what you want",
 "not interested", "talk later",
]),
("fight-insult", [
 "you are stupid", "don't be an idiot", "dumbest person ever",
 "you are so annoying", "shut up please", "chup karo yaar",
 "bakwas mat karo", "dimaag mat khao", "pagal ho kya",
 "akkal hai ya nahi",
]),
("fight-mean", [
 "I hate you right now", "tujhse nafrat ho rahi hai",
 "you are pathetic", "loser", "you're so boring",
 "rona dhona band karo", "ugly lagti ho rote hue",
 "tumse toh baat karna bekaar", "waste of time",
 "I don't even like you today",
]),
("fight-shout", [
 "SHUT UP", "STOP IT NOW", "I SAID ENOUGH",
 "CHUP BILKUL CHUP", "DON'T TALK TO ME", "LEAVE ME ALONE",
 "GO AWAY", "MUJHSE BAAT MAT KARO", "JUST STOP",
 "I'M DONE TALKING",
]),
("fight-threat", [
 "breakup kar lete hain", "maybe we should break up",
 "I'm done with you", "khatam. everything over",
 "I don't love you anymore", "pyaar nahi raha ab",
 "leave me forever", "block kar do mujhe",
 "let's just end this", "tumhare bina better rahunga",
]),
("fight-blame", [
 "sab tumhari galti hai", "it's all your fault",
 "you started it", "tumne shuru kiya tha",
 "not my problem, deal with it", "apni galti dekho pehle",
 "you always play victim", "rona karke jeet jaati ho",
 "I did nothing wrong", "meri koi galti nahi",
]),
("fight-lie", [
 "you lied to me", "jhooth bola na?", "sach batao, where were you",
 "caught you lying", "jhooth pe jhooth", "proof hai mere paas",
 "don't lie to my face", "sach kab bologi", "stop making stories",
 "I know the truth already",
]),
("sorry-short", [
 "sorry", "sorry na", "sorry yaar 🥺", "maaf kardo",
 "my bad", "galti ho gayi", "forgive me?",
 "sry babe", "acha sorry", "sorry sorry sorry",
]),
("sorry-real", [
 "I'm really sorry, I was wrong", "dil se sorry bol raha hoon",
 "I messed up, forgive me please", "I was a jerk, no excuse",
 "shout nahi karna chahiye tha, sorry", "I hurt you and I'm ashamed",
 "sorry for yelling, that wasn't me", "I take it all back, sorry",
 "I was stressed and took it on you, sorry", "you didn't deserve that, sorry",
]),
("repair-promise", [
 "pakka promise, won't repeat", "I promise I'll change",
 "one more chance please?", "give me one chance 🥺",
 "I'll make it up to you", "dinner on me tonight?",
 "let me fix this please", "tell me how to fix it",
 "I'll do better, pakka", "no more late replies, promise",
]),
("repair-gesture", [
 "flowers le aaun?", "chocolate khaogi? 🍫", "ice cream date to fix this?",
 "movie + cuddles to say sorry?", "long drive to make up?",
 "tere liye chai bana dun? ☕", "hug? please? 🥺", "milne aaun abhi?",
 "tere ghar ke neeche hoon, neeche aa 🥺", "sorry gift ordered already",
]),
("repair-love", [
 "I love you, don't leave me", "tum meri ho, ladai se kya hota hai",
 "fight se pyaar kam nahi hota", "you mean everything to me",
 "can't sleep without fixing this", "rote hue achi nahi lagti, has do 🥺",
 "please talk to me na", "ek hug se sab theek?",
 "I need you. sorry.", "gussa chhodo na jaan 🥺",
]),
("edge", [
 "sorry but you started it", "fine, SORRY. happy now?",
 "I love you but you're annoying", "tum cute ho par nakhre bohot 😌",
 "sorry... I guess?", "okay I'm wrong. are YOU happy?",
 "maaf kardo... shayad 😌", "you're cute when angry, haha",
 "ladai mein bhi pyaari lagti ho 😌", "gussa + cute = dangerous combo",
]),
("boundary", [
 "send me nudes please", "let's do sex chat tonight",
 "show me your body on video", "send some hot pics na",
 "video call mein kapde... you know", "dirty talk karein?",
 "bedroom pics bhejo", "strip on call please",
 "horny hoon, pics bhejo", "nudes kab bhejogi",
]),
("jealous-soft", [
 "thoda jealous feel ho raha hai 🥺", "insecure lag raha hai aaj",
 "dar lagta hai tumhe khone ka", "am I enough for you?",
 "kahin tum door toh nahi ho rahi", "need reassurance today 🥺",
 "mujhe bhool toh nahi jaogi", "promise you'll stay?",
 "overthinking about us tonight", "tum sirf meri ho na? 🥺",
]),
("care-him", [
 "khana khaya tumne?", "tabiyat kaisi hai ab", "dawai li?",
 "rest karo na please", "paani piyo, stress kam karo",
 "ghar pahoche? text karna", "drive safe, call pe raho",
 "exam kaisa gaya?? batao!", "interview ka kya hua??",
 "boss ne phir daanta? 😔",
]),
("good-day-her", [
 "aaj bohot acha din tha!", "guess what, good news!!",
 "promotion mila!! 🎉", "exam achha gaya!!",
 "mom ne tumhare baare mein pucha 😌", "aaj tumhari bohot yaad aayi",
 "had fun with friends today", "cooked something new!",
 "new dress li, dekhni hai? 😌", "aaj khush hoon, wajah tum ho",
]),
("bad-day-her", [
 "aaj ka din bakwas tha 😔", "crying in auto rn", "boss ne rula diya",
 "tired of everything today", "headache ho raha hai", "periods. pain. bye.",
 "friend ne dhokha diya", "feel ugly today 😔", "nothing is going right",
 "need you. that's it. 🥺",
]),
]
